### ISSUE TITLE
Weird Font Change

### ISSUE THREAD

**Issue by sarptekbas** [The-Burning/blackeye-im#19]
I installed blackeye-im on Ubuntu WSL2 but when I want to type anything after running blackeye, font changes to random characters. 
![WindowsTerminal_pnevV68Er8](https://user-images.githubusercontent.com/47891877/124389963-2f60c700-dcf2-11eb-8785-0f38c4d693bf.png)

**Comment by sarptekbas** [comment]
I tested An0nUD4Y/blackeye as well and the same thing happens.

**Comment by LoRdSoban** [comment]
Same here on Kali WSL2 too.
![image](https://user-images.githubusercontent.com/62153801/124804738-123b2b00-df74-11eb-8c47-efd30cefdae5.png)

**Comment by sarptekbas** [comment]
> Same here on Kali WSL2 too.
> ![image](https://user-images.githubusercontent.com/62153801/124804738-123b2b00-df74-11eb-8c47-efd30cefdae5.png)

As I found out, that is an issue with the WSL itself. You can use VMware Workstation.

**Comment by Git-Ankitraj** [comment]
I don't get why people use WSL when they can dual boot Linux and windows.

**Comment by sarptekbas** [comment]
> I don't get why people use WSL when they can dual boot Linux and windows.

Because people don’t want to reboot again everytime they want to use linux (or Windows).

**Comment by sarptekbas** [comment]
[Closing] Problem is caused by the Windows’ formatting or the WSL itself. Solution: Use VM or a live usb.
