### ISSUE TITLE
The ngrok link issue has been fixed and the ngrok is working pretty fine without that red warning screen of google chrome.

### ISSUE THREAD

**Issue by The-Burning** [The-Burning/blackeye-im#25]

**Comment by vikashchand** [comment]
yes this is working but its not working properly on google cloud terminal ,there its alwaysing giving tunnel not found error,do u have any idea how to fix that

**Comment by stevengreg2020** [comment]
well i have been trying this for days now and all i discovered about it is that i can access the it in my windows computer with same network service provider but if i sent the ngrok link outside to my friend or sister outside my city using a different network service provider it cant be accessed from another network service provider only on same computer connected with same network with my home network. please someone should help this is really making this whole thing looks useless

**Comment by mordehai1o2** [comment]
Can anyone help me I'm having a problem that it does not give the link to send

**Comment by stevengreg2020** [comment]
> _No description provided._

i really dont know why this Burning Boy dont reply to issues why i drop a complained for days now and you have not yet replied to me the problem or the solution how do you make a good teacher when you dont reply to people who are learning from you this is not nice.??

**Comment by The-Burning** [comment]
> well i have been trying this for days now and all i discovered about it is that i can access the it in my windows computer with same network service provider but if i sent the ngrok link outside to my friend or sister outside my city using a different network service provider it cant be accessed from another network service provider only on same computer connected with same network with my home network. please someone should help this is really making this whole thing looks useless

The problem you have mentioned has already been fixed months ago. I have tested it thoroughly and is working fine.

**Comment by The-Burning** [comment]
> > _No description provided._
> 
> i really dont know why this Burning Boy dont reply to issues why i drop a complained for days now and you have not yet replied to me the problem or the solution how do you make a good teacher when you dont reply to people who are learning from you this is not nice.??

Bud! I have a lot of other things to do as well rather than replying for issues which has already been assessed.
