### ISSUE TITLE
How to use link outside of own LAN.

### ISSUE THREAD

**Issue by beanboyy** [The-Burning/blackeye-im#3]
How do you change the ip address to a private one or etc so it works outside of own LAN.

**Comment by Git-Ankitraj** [comment]
It works on both LAN and over the internet, you just need to share the generated ngrok link to the victim.

**Comment by topgas** [comment]
when i share the link it dosent go online

**Comment by mojaas** [comment]
> It works on both LAN and over the internet, you just need to share the generated ngrok link to the victim.

it works with lan but not over the internet. when my friend over the internet opens the link it shows tunnel not found

**Comment by mojaas** [comment]
help me pleaseeeee . just installed kali and ubuntu and i typed your command but it only works for LAN i even triedd running ngrok setting hhtp 3000 but did work, only LAN

**Comment by mojaas** [comment]
> when i share the link it dosent go online

same

**Comment by stevengreg2020** [comment]
> It works on both LAN and over the internet, you just need to share the generated ngrok link to the victim.

is not working outside the my home network. and is making this whole experiment looks useless. please any solution to this.??

**Comment by Singh-00** [comment]
I do have the same problem has anyone came up with a solution till now?
