### ISSUE TITLE
Language changes after ./blackeye.sh

### ISSUE THREAD

**Issue by datascientist-saad** [The-Burning/blackeye-im#32]
![Screenshot (81)](https://user-images.githubusercontent.com/54408261/143669716-ef0b44a1-ee4d-46bf-bc59-ac5c9191fb45.png)

**Comment by clkdecember14** [comment]
I am having this same problem.

**Comment by irajoeirajoe** [comment]
How did you fix it?

**Comment by caseyKoehn** [comment]
I switched to a Linux operating system.
