### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by NightXxXxX** [The-Burning/blackeye-im#37]
Hello, I’m new to GitHub so I don’t know if it’s the right place to ask questions.But How can you add more webpages in this tool ???

**Comment by The-Burning** [comment]
You have to create html (with php) sites as similar or exact to the real
ones and add those html and php files to the /sites folder.

**Comment by The-Burning** [comment]
Also you need to list the newly built site in 'blackeye.sh' script if you
know how to do it properly.

**Comment by NightXxXxX** [comment]
Thank you for replying, I did what you said but it didn’t work out.(I dumped the login.html from the webpage and copied the PayPals php files ( I looked the other folders too all the php files look the same )the only thing that I changed is the index.php file if I remember correctly 

now I pasted the link in my browser, it kinda worked cause i’m now in the fake page. I have typed the email and the password.I’m pressing the log in button and nothing happens. It stays the same it didn’t even redirected me to the real webpage. Also It doesn’t show any picture. I’m lost

**Comment by NightXxXxX** [comment]
Hi , I did the <form action=‘’login.php’’ method=‘’post’’
Kinda working now but it doesn’t catch the account and password, what’s the problem here ?

Credentials Found!
Account: (blank)
Password:(blank)

Also I’m not interested on PayPal (PayPal was in blackeye-im) or in anything illegal 
Im just very curious how certain things work 
:)
